In [1]:
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt

rng = np.random.default_rng()

In [2]:
def rayleigh_quotient(A, x):
    """
    Returns the Rayleigh quotient of x given A. The Rayleigh quotient
    is the scalar $r$ which minimizes $||Ax - rx||$, and thus is like
    an eigenvalue estimate.
    """
    
    r = x.transpose() @ A @ x / np.dot(x,x)
    return r

def power_iteration(A, v_0=None, iterations=1000):
    """
    Given A, estimates the largest eigenvalue of A and corresponding
    eigenvector via power iteration.
    """
    
    # Check matrix for squareness and symmetry
    assert A.ndim == 2, "Must be a matrix"
    assert np.shape(A)[0] == np.shape(A)[1], "Matrix dimensions must agree"
    tol = 1e-12
    assert np.max(np.abs(A - A.transpose())) <= tol, "Matrix should be symmetric"
    n = np.shape(A)[0]
    
    # Initialization
    if v_0 is None:
        v_0 = rng.random(n)
        v_0 = v_0 / linalg.norm(v_0)
    
    # Iteration
    v = v_0
    for k in range(iterations):
        w = A @ v
        v = w / linalg.norm(w)
        eigval = rayleigh_quotient(A, v)
        
    return v, eigval

def inverse_iteration(A, mu, v_0=None, iterations=1000):
    """
    Given A, estimates the eigenvalue of A closest to mu via inverse
    iteration (and the corresponding eigenvector).
    """
    
    # Check matrix for squareness and symmetry
    assert A.ndim == 2, "Must be a matrix"
    assert np.shape(A)[0] == np.shape(A)[1], "Matrix dimensions must agree"
    tol = 1e-12
    assert np.max(np.abs(A - A.transpose())) <= tol, "Matrix should be symmetric"
    n = np.shape(A)[0]
    
    # Initialization
    if v_0 is None:
        v_0 = rng.random(n)
        v_0 = v_0 / linalg.norm(v_0)
    
    # Iteration
    v = v_0
    for k in range(iterations):
        B = A - mu*np.eye(n)
        w = linalg.solve(B, v, assume_a='sym')
        v = w / linalg.norm(w)
        eigval = rayleigh_quotient(A, v)
    return v, eigval

# Bonus: Rayleigh quotient iteration
def rayleigh_quotient_iteration(A, v_0=None, iterations=20):
    """
    Given A, estimates the eigenvalue of A closest to mu via Rayleigh quotient
    iteration (and the corresponding eigenvector).
    """
    
    # Check matrix for squareness and symmetry
    assert A.ndim == 2, "Must be a matrix"
    assert np.shape(A)[0] == np.shape(A)[1], "Matrix dimensions must agree"
    tol = 1e-12
    assert np.max(np.abs(A - A.transpose())) <= tol, "Matrix should be symmetric"
    n = np.shape(A)[0]
    
    # Initialization
    if v_0 is None:
        v_0 = rng.random(n)
        v_0 = v_0 / linalg.norm(v_0)
    
    # Iteration
    v = v_0
    eigval = rayleigh_quotient(A, v)
    for k in range(iterations):
        B = A - eigval*np.eye(n)
        w = linalg.solve(B, v, assume_a='sym')
        v = w / linalg.norm(w)
        eigval = rayleigh_quotient(A, v)
    return v, eigval

In [3]:
# Construct symmetric matrix
B = rng.integers(-3, 4, size=(3,3))
A = B.transpose() @ B
A

array([[12,  8, -8],
       [ 8, 14, -1],
       [-8, -1, 14]])

In [4]:
v1, lam1 = power_iteration(A)

In [5]:
# Eigenvector found
v1

array([ 0.65900213,  0.53184405, -0.53184405])

In [6]:
# Check difference A v - lambda v
A @ v1 - lam1 * v1

array([0., 0., 0.])

In [7]:
# Inverse iteration
v_other, lam_other = inverse_iteration(A, 1.0)

In [8]:
# Eigenvector found
v_other

array([ 0.75214107, -0.46598487,  0.46598487])

In [9]:
# Check difference A v - lambda v
A @ v_other - lam_other * v_other

array([-4.44089210e-16, -9.99200722e-16, -1.11022302e-16])