# Introduction to numpy

Numpy is a package which has mathematical functions and data structures for dealing with vectors.

In [3]:
import numpy as np

## Example constants and functions in numpy:

In [4]:
# Example constants
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


In [5]:
# Example functions
print(np.sqrt(2))

1.4142135623730951


In [6]:
print(np.sin(np.pi / 2))
print(np.exp(2))
print(np.log10(1000))

1.0
7.38905609893065
3.0


## 1D Arrays
* `np.array`
* `np.arange`
* `np.linspace`
* Slicing and indexing arrays

### Why numpy arrays?
We need numpy to deal with arrays of numbers in a mathematical way.

In [7]:
# Using python lists results in bad math:
[1, 2, 3] + [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [8]:
# Math works the way you would expect with numpy arrays:
np.array([1, 2, 3]) + np.array([1, 2, 3])

array([2, 4, 6])

Numpy functions work elementwise on arrays:

In [9]:
arr = np.array([1, 2, 3, 4, 5])
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

### np.arange
Use np.arange for ranges of numbers:

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [13]:
np.arange(100, 90, -1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91])

Note: you can get information about a class or function by calling help() on it:

In [14]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In jupyterlab, you can also use the question mark operator:

In [15]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

### np.linspace
Use np.linspace to linearly interpolate between two numbers

In [16]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [17]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
np.linspace(0, 1, 10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### Indexing and slicing arrays
Slicing provides a quick way of subsetting arrays.

In [19]:
x = np.arange(5, 20)
print(x)
print(x[1])
print(x[1:10])
print(x[1:10:2])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
6
[ 6  7  8  9 10 11 12 13 14]
[ 6  8 10 12 14]


## 2D arrays
* `np.reshape`
* `np.zeros`
* `np.ones`
* `np.transpose`
* `np.shape`

In [20]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

Get the shape of the array using `array.shape`:

In [21]:
M.shape

(2, 3)

Get the size using `array.size`:

In [22]:
M.size

6

Indexing: first dimension is the row index, second dimension is the column axis

In [23]:
M[0, 2]

3

Slicing is similar to the 1D case:

In [24]:
# Zeroth row
print(M[0,:])

# Zeroth and first columns
print(M[:, 0:2])

[1 2 3]
[[1 2]
 [4 5]]


You can reshape arrays using array.reshape:

In [25]:
x = np.arange(1, 10)
A = x.reshape(3, 3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Create a matrix or vector of ones using `np.ones` (similar function `np.zeros`)

In [26]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Using "+", "-", "*", "/" or "**" operators results in elementwise operations.

In [27]:
# Not real matrix multiplication
A * B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Use '@' operator for matrix multiplication:

In [28]:
A @ B

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])