In [1]:
import numpy as np

In [2]:
def lu(A):
    """
    Given an nxn matrix A, computes the LU decomposition without
    pivoting.
    
    Parameters:
        A : np.ndarray
    Returns
        L, U : np.ndarray
    """
    # Check shapes
    if np.shape(A)[0] != np.shape(A)[1]:
        raise ValueError("Matrix dimensions should be the same length")
    
    n = np.shape(A)[0]
    L = np.eye(n)
    U = np.zeros((n,n))
    
    # Set first row
    U[0, :] = A[0, :]
    
    for i in np.arange(2, n+1):
        for j in np.arange(1, i):
            # L_ij factors
            sum_prod = np.sum(
                [L[i-1, k-1]*U[k-1, j-1] for k in np.arange(1, j)]
            )
            L[i-1, j-1] = 1/U[j-1, j-1] * (A[i-1, j-1] - sum_prod)
            
        for j in np.arange(i, n+1):
            # U_ij factors
            sum_prod = np.sum(
                [L[i-1, k-1]*U[k-1, j-1] for k in np.arange(1, i)]
            )
            U[i-1, j-1] = A[i-1, j-1] - sum_prod
    
    return L, U

For the above loops we could have used np.dot and a condensed notation instead of the list comprehension:

```python
# Condensed version of above loops without list comprehensions
for i in np.arange(2, n+1):
    for j in np.arange(1, i):
        l_ij_sum = np.dot(L[i-1, 0:j-1], U[0:j-1, j-1])
        L[i-1, j-1] = 1/U[j-1, j-1] * (A[i-1, j-1] - l_ij_sum)
    for j in np.arange(i, n+1):
        U[i-1, j-1] = A[i-1, j-1] - np.dot(L[i-1, 0:i-1], U[0:i-1, j-1])
```

In [3]:
A = np.array([
    [3, 3, 0],
    [6, 4, 7],
    [-6, -8, 9]
])

L, U = lu(A)
print("Matrix L:")
print(L)
print("Matrix U:")
print(U)

Matrix L:
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-2.  1.  1.]]
Matrix U:
[[ 3.  3.  0.]
 [ 0. -2.  7.]
 [ 0.  0.  2.]]


In [4]:
L @ U

array([[ 3.,  3.,  0.],
       [ 6.,  4.,  7.],
       [-6., -8.,  9.]])