In [1]:
import numpy as np
from lu_utils import lu

## Stability of LU

Consider
$$
A =
\begin{bmatrix}
    10^{-20} & 1 \\
    1 & 1
\end{bmatrix}
$$
The LU factors of this matrix are 
$$
L =
\begin{bmatrix}
    1 & 0 \\
    10^{20} & 1
\end{bmatrix}, \hspace{1cm}
U =
\begin{bmatrix}
    10^{-20} & 1 \\
    0 & 1 - 10^{20}
\end{bmatrix}
$$

But we see that if we try to compute these matrices on a computer, we get something slightly different:

In [2]:
A = np.array([
    [1e-20, 1],
    [1, 1]
])

In [3]:
L_comp, U_comp = lu(A)

In [4]:
print("Computed L:")
print(L_comp)
print("Computed U:")
print(U_comp)

Computed L:
[[1.e+00 0.e+00]
 [1.e+20 1.e+00]]
Computed U:
[[ 1.e-20  1.e+00]
 [ 0.e+00 -1.e+20]]


The computed matrices are 
$$
\tilde{L} =
\begin{bmatrix}
    1 & 0 \\
    10^{20} & 1
\end{bmatrix}, \hspace{1cm}
\tilde{U} =
\begin{bmatrix}
    10^{-20} & 1 \\
    0 & -10^{20}
\end{bmatrix}
$$

These seem like they're "close enough", but we see that the product $\tilde{L}\tilde{U}$ is nowhere close to A:

In [11]:
print(L_comp @ U_comp)

[[1.e-20 1.e+00]
 [1.e+00 0.e+00]]


Fortunately, pivoting typically makes LU better:

In [8]:
P = np.array([
    [0, 1],
    [1, 0]
])

# Permuted matrix

print("Computed permuted matrix PA:")
print(P @ A)

Computed permuted matrix PA:
[[1.e+00 1.e+00]
 [1.e-20 1.e+00]]


In [9]:
L_p, U_p = lu(P @ A)

In [10]:
print(L_p @ U_p)

[[1.e+00 1.e+00]
 [1.e-20 1.e+00]]
